### ISSUE TITLE
메인 홈 화면 작업

### ISSUE THREAD

**Issue by seocylucky** [Advent-calendar-by-likeLion/AdventCalendar-test-repo#6]
## Issue: ⚒️ FEATURE
메인 홈 화면 작업

## Description
sef 버전 메인 홈 화면 작업입니다.
<img width="200" alt="image" src="https://github.com/Advent-calendar-by-likeLion/AdventCalendar-test-repo/assets/94633589/7bd11b58-1209-40c9-98f2-9dad6a20135d">

## Todo
- [ ] 배경
   - [ ] 파티클
   - [ ] 캐릭터 세 개
   - [ ] 진저 호텔
   - [ ] 헤더 제목(진저호텔 x sef2023)
- [ ] 버튼 두 개
   - [ ] sef에게 편지 쓰기 버튼
   - [ ] 진저호텔에게 편지 쓰기 버튼

## ETC
기타사항
